FROM oven/bun:1.3.5-alpine

WORKDIR /app

# Устанавливаем зависимости (копируем только package.json для кеширования)
COPY package.json bun.lock* ./
COPY tsconfig.json ./
COPY apps/frontend/package.json ./apps/frontend/package.json
COPY packages/shared/package.json ./packages/shared/
COPY packages/shared ./packages/shared

# Устанавливаем зависимости
RUN bun install

EXPOSE 5173

# Запуск Vite dev server
WORKDIR /app/apps/frontend
CMD ["bun", "run", "dev", "--host"]