FROM oven/bun:1.3.5-alpine

WORKDIR /app

RUN apk add --no-cache nodejs npm

COPY package.json bun.lock ./
COPY apps/backend/package.json ./apps/backend/package.json
COPY apps/frontend/package.json ./apps/frontend/package.json
COPY apps/admin/package.json ./apps/admin/package.json
COPY packages/shared/package.json ./packages/shared/package.json
COPY packages/message-types/package.json ./packages/message-types/package.json

RUN bun install --frozen-lockfile

EXPOSE 5175

WORKDIR /app/apps/admin
CMD ["npm", "run", "dev"]
