FROM oven/bun:1.3.5-alpine

WORKDIR /app

RUN apk add --no-cache nodejs npm

COPY package.json bun.lock ./
COPY apps/backend/package.json ./apps/backend/package.json
COPY apps/frontend/package.json ./apps/frontend/package.json
COPY apps/deckEditor/package.json ./apps/deckEditor/package.json
COPY packages/shared/package.json ./packages/shared/package.json

RUN bun install --frozen-lockfile

EXPOSE 5174

WORKDIR /app/apps/deckEditor
CMD ["npm", "run", "dev"]
